#
# User-owned CMake fragment: BMI088 IMU driver.
#
# STM32CubeMX rewrites cmake/stm32cubemx/CMakeLists.txt on every "Generate Code",
# which is why the BMI088 sources used to disappear from the build. This file is
# NOT generated by CubeMX, so it survives every regeneration.
#
# It is pulled in by a single `include(cmake/bmi088.cmake)` line in the root
# CMakeLists.txt (a file CubeMX only writes once, on the very first generation).
# If that line ever goes missing, just add it back - no other change is needed.
#

set(BMI088_DIR ${CMAKE_CURRENT_LIST_DIR}/../Device/BMI088)

# Object library: the objects are always linked into the executable,
# just like when the sources were listed directly in the executable target.
add_library(bmi088 OBJECT
    ${BMI088_DIR}/BMI088driver.c
    ${BMI088_DIR}/BMI088Middleware.c
)

# Driver headers (the host application includes "BMI088driver.h")
target_include_directories(bmi088 PUBLIC
    ${BMI088_DIR}/inc
)

# Inherit the STM32CubeMX include paths and symbols (main.h, spi.h, HAL, CMSIS)
target_link_libraries(bmi088 PUBLIC stm32cubemx)

# Attach to the project executable.
# NOTE: plain signature - the root CMakeLists.txt also uses the plain form,
# mixing plain and keyword signature for the same target is an error.
target_link_libraries(${CMAKE_PROJECT_NAME} bmi088)
