#
# User-owned CMake fragment: WS2812 on-board RGB indicator.
#
# Same idea as cmake/bmi088.cmake: this file is NOT generated by STM32CubeMX,
# so it survives every "Generate Code" run - only cmake/stm32cubemx/CMakeLists.txt
# gets rewritten. It is pulled in by one `include(cmake/ws2812.cmake)` line in the
# root CMakeLists.txt (generated once, on the very first generation).
#

set(WS2812_DIR ${CMAKE_CURRENT_LIST_DIR}/../Device/WS2812)

# Object library: the objects are always linked into the executable,
# just like when the sources are listed directly in the executable target.
add_library(ws2812 OBJECT
    ${WS2812_DIR}/ws2812.c
)

# Driver headers (the host application includes "ws2812.h")
target_include_directories(ws2812 PUBLIC
    ${WS2812_DIR}/inc
)

# Inherit the STM32CubeMX include paths and symbols (main.h, spi.h, HAL, CMSIS)
target_link_libraries(ws2812 PUBLIC stm32cubemx)

# Attach to the project executable.
# NOTE: plain signature - the root CMakeLists.txt also uses the plain form,
# mixing plain and keyword signature for the same target is an error.
target_link_libraries(${CMAKE_PROJECT_NAME} ws2812)
